# Generated by Django 4.2.16 on 2024-11-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(upload_to='appProfile/images/'),
        ),
    ]
