# Generated by Django 4.2.16 on 2024-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0002_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artistCheck',
            field=models.BooleanField(default=False),
        ),
    ]
